set_volume_steps:
  name: Set Volume Steps
  description: Set the Volume Change % in your Phoniebox
  target:
    entity:
      integration: phoniebox
      domain: media_player
  fields:
    volume_steps:
      name: Steps
      description: Volume steps to set.
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1

set_max_volume:
  name: Set Maximum Volume
  description: Set the maximum Volume of your Phoniebox
  target:
    entity:
      integration: phoniebox
      domain: media_player
  fields:
    max_volume:
      name: Max. Volume
      description: Maximum Volume to set.
      required: true
      selector:
        number:
          min: 0
          max: 100
          step: 1

set_idle_shutdown_timer:
  name: Set Idle Shutdown Timer
  description: Set the idle shutdown timer of your Phoniebox
  target:
    entity:
      integration: phoniebox
      domain: media_player
  fields:
    idle_time:
      name: Idle Time
      description: Time that phoniebox is idle till shutdown. 0 to turn idle timer off.
      required: true
      selector:
        number:
          min: 0
          max: 60
          step: 1