name-template: "v$RESOLVED_VERSION"
tag-template: "v$RESOLVED_VERSION"
change-template: "- #$NUMBER $TITLE @$AUTHOR"
sort-direction: ascending
categories:
  - title: ":boom: Breaking changes"
    label: "pr: breaking"

  - title: ":sparkles: Features"
    label: "pr: feat"

  - title: ":recycle: Refactor"
    label: "pr: refactor"

  - title: ":bug: Bug Fixes"
    label: "pr: fix"

  - title: ":zap: Performance Improvements"
    labels: "pr: perf"

autolabeler:
  - label: "pr: breaking"
    body:
      - "/BREAKING CHANGE/"
  - label: "pr: test"
    branch:
      - 'test\/.+/'
  - label: "pr: style"
    branch:
      - 'style\/.+/'
  - label: "pr: refactor"
    branch:
      - '/refactor\/.+/'
  - label: "pr: perf"
    branch:
      - '/perf\/.+/'
  - label: "pr: fix"
    branch:
      - '/fix\/.+/'
  - label: "pr: ci"
    branch:
      - '/ci\/.+/'
  - label: "pr: build"
    branch:
      - '/build\/.+/'
  - label: "pr: docs"
    files:
      - "*.md"
    branch:
      - '/docs{0,1}\/.+/'
  - label: "pr: feat"
    branch:
      - '/feature\/.+/'

include-labels:
  - "pr: breaking"
  - "pr: fix"
  - "pr: feat"
  - "pr: perf"
  - "pr: refactor"

version-resolver:
  major:
    labels:
      - "pr: breaking"
  minor:
    labels:
      - "pr: feat"
      - "pr: perf"
      - "pr: refactor"
  patch:
    labels:
      - "pr: fix"
  default: minor

template: |
  [![Downloads for this release](https://img.shields.io/github/downloads/c0un7-z3r0/hass-phoniebox/v$RESOLVED_VERSION/total.svg)](https://github.com/c0un7-z3r0/hass-phoniebox/releases/v$RESOLVED_VERSION)
  $CHANGES

  ## Links
    - [How to submit bugs/feature requests](https://github.com/c0un7-z3r0/hass-phoniebox/issues)
